String.prototype.isLengthGreaterThan = function(limit) {
    return this.length > limit; //the this will point to that string object
}
//added a method to the prototype so all strings instantly have access to this new method 
//can add features 

console.log("John".isLengthGreaterThan(3)); 
//"John" the primitive string was turned into a String object generated by the String function constructor
//and then it will have access to the String.prototype property and the new method created on top

Number.prototype.isPositive = function() {
    return this > 0;
}
//js will convert string for you automatically, it will not convert a number for you automatically
//3.isPositive() would cause an error unless you built a new Number object, 3 first.
//var a = new Number(3)
//a.isPositive()